# -*- coding: utf-8 -*-
"""app_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQkuPx2Xb6nVPmonxBmut1gb0UbQyc39
"""

pip install streamlit pandas requests

import streamlit as st
import pandas as pd
import requests
from datetime import datetime

# Page setup
# Removed 'title' keyword argument based on the TypeError
st.set_page_config(layout="wide")
st.markdown("<h1 style='text-align:center;'>📈 Live Stock Price Dashboard</h1>", unsafe_allow_html=True)

# Sidebar inputs
with st.sidebar:
    st.header("Configure Stock")
    API_KEY = st.text_input("Alpha Vantage API Key", value="X7UK3IP1BY6ZA91I", type="password")
    symbol = st.text_input("Ticker Symbol", value="AAPL").upper()
    interval = st.selectbox("Time Interval", ["1min","5min","15min","30min","60min"])
    st.markdown("---")
    show_chart = st.checkbox("Show Intraday Chart", value=True)

# Function to load data
@st.cache_data(ttl=60)
def fetch_data(sym, interval, api_key):
    url = (
        f"https://www.alphavantage.co/query"
        f"?function=TIME_SERIES_INTRADAY&symbol={sym}"
        f"&interval={interval}&apikey={api_key}&outputsize=compact"
    )
    resp = requests.get(url)
    data = resp.json()
    ts = data.get(f"Time Series ({interval})", {})
    df = pd.DataFrame.from_dict(ts, orient="index").astype(float)
    df.index = pd.to_datetime(df.index)
    return df

# Fetch and display
if API_KEY and symbol:
    st.subheader(f"Real‑time quotes for {symbol}")
    try:
        df = fetch_data(symbol, interval, API_KEY)
        latest = df.iloc[0]
        col1, col2, col3 = st.columns(3)
        col1.metric("📅 Last Timestamp", df.index[0].strftime("%Y-%m-%d %H:%M"))
        col2.metric("💲 Price", f"${latest['4. close']:.2f}", delta=f"{(latest['4. close']-latest['1. open']):+.2f}")
        col3.metric("⏫ High / ⏬ Low", f"${latest['2. high']:.2f} / ${latest['3. low']:.2f}")

        if show_chart:
            st.line_chart(df['4. close'], use_container_width=True)
    except Exception as e:
        st.error(f"Failed to retrieve data: {e}")
else:
    st.warning("🔑 Enter API key and symbol above")

import streamlit as st

st.title("🎶 Video + Music Player")

# Assuming the files are in a subdirectory named 'media'
try:
    video_bytes = open("media/my_video.mp4", "rb").read()
    audio_bytes = open("media/music.mp3", "rb").read()

    st.video(video_bytes)
    st.audio(audio_bytes, format="audio/mp3", loop=True, autoplay=False)
except FileNotFoundError:
    st.error("Make sure 'my_video.mp4' and 'music.mp3' are in the correct directory.")